package p.l.e.x.u.s

enum class PlexusAction {
    WIFI_P2P_DISCOVERY_CHANGED_ACTION,
    WIFI_P2P_PEERS_CHANGED_ACTION,
    WIFI_P2P_STATE_CHANGED_ACTION,
    WIFI_P2P_CONNECTION_CHANGED_ACTION,
    WIFI_P2P_THIS_DEVICE_CHANGED_ACTION
}